import {
  CoaComplianceVerdict,
  Conclusion,
  DeptName,
  Role,
} from "@prisma/client";
import type { Tx } from "../lib/prisma-types";
import { AppError } from "../lib/app-error";
import { findDepartmentIdByName } from "../modules/notifications/notifications.repository";
import * as batchesRepo from "../modules/batches/batches.repository";
import { AuditAction, AuditEntityType, log as auditLog } from "./audit.service";
import { documentLink } from "./notification-links";
import { notify } from "./notification.service";
import {
  formatAcceptanceLimits,
  formatConclusionLabel,
  formatSectionResult,
} from "./render-formatters";

function computeComplianceVerdict(
  conclusions: (Conclusion | null)[],
): CoaComplianceVerdict {
  const allCompliant = conclusions.every(
    (c) => c === Conclusion.SATISFACTORY || c === Conclusion.PASS,
  );
  return allCompliant ? CoaComplianceVerdict.COMPLIES : CoaComplianceVerdict.DOES_NOT_COMPLY;
}

/** TODO Epic 21 — SOP-on-SOP styling: render PDF from coa_results. */
export async function generateCoaPdf(_coaDocId: string): Promise<void> {
  // no-op until Epic 21
}

/** US-12-17 / US-13-1 — auto-generate COA from QA-signed AWS inside the AWS-sign transaction. */
export async function generateCoaFromSignedAws(
  tx: Tx,
  batchId: string,
  signedAwsDocId: string,
  awsDocNo: string,
): Promise<void> {
  const existing = await batchesRepo.findExistingCoaDocument(batchId, tx);
  if (existing) {
    return;
  }

  const coaDoc = await batchesRepo.findPendingCoaDocument(batchId, tx);
  if (!coaDoc) {
    throw AppError.conflict("PENDING COA document not found for batch");
  }

  const awsDoc = await batchesRepo.findBatchDocumentById(signedAwsDocId, tx);
  if (!awsDoc) {
    throw AppError.conflict("Signed AWS document not found for COA generation");
  }

  const sections = await batchesRepo.findAwsSectionsForCoa(signedAwsDocId, tx);

  const coaResultRows = sections.map((section, index) => {
    const specTest = section.specDocumentTest;
    return {
      batchDocumentId: coaDoc.id,
      testName: specTest.testName,
      result: formatSectionResult(specTest.resultType, section.resultDisplay, section.readings),
      acceptanceLimits: formatAcceptanceLimits(specTest),
      conclusion: formatConclusionLabel(section.conclusion),
      sortOrder: specTest.sortOrder ?? index + 1,
    };
  });

  if (coaResultRows.length > 0) {
    await batchesRepo.createCoaResults(coaResultRows, tx);
  }

  const complianceVerdict = computeComplianceVerdict(sections.map((s) => s.conclusion));

  await batchesRepo.transitionCoaDocumentToAutoGenerated(
    coaDoc.id,
    {
      complianceVerdict,
      createdById: awsDoc.createdById,
      qcApprovedById: awsDoc.qcApprovedById,
      qaSignedById: null,
    },
    tx,
  );

  await auditLog(
    {
      userName: "System",
      action: AuditAction.GENERATE,
      entityType: AuditEntityType.COA,
      entityId: coaDoc.id,
      docNo: coaDoc.docNo,
      comment: `auto-generated from signed AWS ${awsDocNo}`,
    },
    tx,
  );

  const qaDeptId = await findDepartmentIdByName(DeptName.QA, tx);
  const batch = await batchesRepo.findBatchById(batchId, tx);
  if (qaDeptId && batch?.batchNo) {
    await notify({
      recipients: { role: Role.QA_MGR, departmentId: qaDeptId },
      type: "COA_GENERATED",
      title: "COA pending sign & issue",
      message: `COA ${coaDoc.docNo} generated for batch ${batch.batchNo}.`,
      link: documentLink(batchId, coaDoc.id),
      tx,
    });
  }

  await generateCoaPdf(coaDoc.id);
}
