import {
  CoaComplianceVerdict,
  Conclusion,
  DeptName,
  DocPhase,
  Operator,
  ResultType,
  Role,
} from "@prisma/client";
import type { SpecDocumentTest } from "@prisma/client";
import type { Tx } from "../lib/prisma-types";
import { AppError } from "../lib/app-error";
import { findDepartmentIdByName } from "../modules/notifications/notifications.repository";
import * as batchesRepo from "../modules/batches/batches.repository";
import { AuditAction, AuditEntityType, log as auditLog } from "./audit.service";
import { documentLink } from "./notification-links";
import { notify } from "./notification.service";

type QualitativeObservation = {
  text?: string;
  passFail?: "PASS" | "FAIL";
};

function decimalToString(value: { toString(): string } | null | undefined): string | null {
  if (value === null || value === undefined) return null;
  return value.toString();
}

export function formatAcceptanceLimits(specTest: SpecDocumentTest): string {
  if (specTest.resultType === ResultType.QUALITATIVE && specTest.acceptanceCriteria) {
    return specTest.acceptanceCriteria;
  }

  const min = decimalToString(specTest.minValue);
  const max = decimalToString(specTest.maxValue);
  const uom = specTest.uom ? ` ${specTest.uom}` : "";

  switch (specTest.operator) {
    case Operator.BETWEEN:
      return `Between ${min} and ${max}${uom}`;
    case Operator.NMT:
      return `NMT ${max}${uom}`;
    case Operator.NLT:
      return `NLT ${min}${uom}`;
    default:
      return specTest.acceptanceCriteria ?? "—";
  }
}

function formatConclusionLabel(conclusion: Conclusion | null): string {
  switch (conclusion) {
    case Conclusion.SATISFACTORY:
      return "Satisfactory";
    case Conclusion.NOT_SATISFACTORY:
      return "Not Satisfactory";
    case Conclusion.PASS:
      return "Pass";
    case Conclusion.FAIL:
      return "Fail";
    default:
      return "—";
  }
}

function formatSectionResult(
  resultType: ResultType,
  resultDisplay: string | null,
  observations: unknown,
): string {
  if (resultType === ResultType.QUANTITATIVE) {
    return resultDisplay ?? "—";
  }

  const obs = (observations ?? {}) as QualitativeObservation;
  if (obs.text?.trim()) {
    return obs.text.trim();
  }
  if (obs.passFail) {
    return obs.passFail === "PASS" ? "Pass" : "Fail";
  }
  return "—";
}

function computeComplianceVerdict(
  conclusions: (Conclusion | null)[],
): CoaComplianceVerdict {
  const allCompliant = conclusions.every(
    (c) => c === Conclusion.SATISFACTORY || c === Conclusion.PASS,
  );
  return allCompliant ? CoaComplianceVerdict.COMPLIES : CoaComplianceVerdict.DOES_NOT_COMPLY;
}

/**
 * TODO Epic 21 — SOP-on-SOP styling: render PDF from coa_results.
 * Reads structured coa_results rows; no file is written in Phase 1.
 */
export async function generateCoaPdf(_coaDocId: string): Promise<void> {
  // no-op until Epic 21
}

export async function generateCoaFromSignedAws(
  tx: Tx,
  batchId: string,
  signedAwsDocId: string,
  awsDocNo: string,
): Promise<void> {
  const coaDoc = await batchesRepo.findPendingCoaDocument(batchId, tx);
  if (!coaDoc) {
    throw AppError.conflict("PENDING COA document not found for batch");
  }

  const awsDoc = await batchesRepo.findBatchDocumentWithWorkflowFields(signedAwsDocId, tx);
  if (!awsDoc) {
    throw AppError.conflict("Signed AWS document not found for COA generation");
  }

  const sections = await batchesRepo.findAwsSectionsForCoaGeneration(signedAwsDocId, tx);

  await batchesRepo.deleteCoaResults(coaDoc.id, tx);

  const coaResultRows = sections.map((section) => {
    const specTest = section.specDocumentTest;
    const resultType =
      specTest?.resultType ?? section.testParameter.resultType;
    const testName =
      specTest?.testName ?? section.testParameter.testName;

    return {
      batchDocumentId: coaDoc.id,
      testName,
      result: formatSectionResult(
        resultType,
        section.resultDisplay,
        section.observations,
      ),
      acceptanceLimits: specTest
        ? formatAcceptanceLimits(specTest)
        : "—",
      conclusion: formatConclusionLabel(section.conclusion),
      sortOrder: section.sortOrder,
    };
  });

  if (coaResultRows.length > 0) {
    await batchesRepo.createCoaResults(coaResultRows, tx);
  }

  const complianceVerdict = computeComplianceVerdict(
    sections.map((s) => s.conclusion),
  );

  await batchesRepo.transitionCoaDocumentToAutoGenerated(
    coaDoc.id,
    {
      complianceVerdict,
      createdById: awsDoc.submittedById,
      qcApprovedById: awsDoc.qcApprovedById,
      qaSignedById: awsDoc.qaSignedById,
    },
    tx,
  );

  await batchesRepo.updateBatchPhase(batchId, DocPhase.COA, tx);

  await auditLog(
    {
      userName: "System",
      action: AuditAction.GENERATE,
      entityType: AuditEntityType.COA,
      entityId: coaDoc.id,
      docNo: coaDoc.docNo,
      comment: `auto-generated from signed AWS ${awsDocNo}`,
    },
    tx,
  );

  const qaDeptId = await findDepartmentIdByName(DeptName.QA, tx);
  const batch = await batchesRepo.findBatchByIdForNotification(batchId, tx);
  if (qaDeptId && batch?.batchNo) {
    await notify({
      recipients: { role: Role.QA_MGR, departmentId: qaDeptId },
      type: "COA_GENERATED",
      title: "COA pending sign & issue",
      message: `COA ${coaDoc.docNo} generated for batch ${batch.batchNo}.`,
      link: documentLink(batchId, coaDoc.id),
      tx,
    });
  }

  await generateCoaPdf(coaDoc.id);
}
